import type { LanguageCode } from './constants';

export const dictionary = {
  en: {
    home: 'Home',
    catalog: 'Catalog',
    flashDeals: 'Flash Deals',
    trending: 'Trending',
    sellWithUs: 'Sell With Us',
    search: 'Search products, brands, categories...',
    searchPlaceholder: 'Search millions of products...',
    cart: 'Cart',
    wishlist: 'Wishlist',
    account: 'Account',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    signOut: 'Sign Out',
    dashboard: 'Dashboard',
    admin: 'Admin',
    seller: 'Seller',
    categories: 'Categories',
    allCategories: 'All Categories',
    featured: 'Featured',
    newArrivals: 'New Arrivals',
    topRated: 'Top Rated',
    bestSellers: 'Best Sellers',
    recommended: 'Recommended For You',
    recommendedDesc: 'AI-curated picks based on your activity',
    viewAll: 'View All',
    shopNow: 'Shop Now',
    addToCart: 'Add to Cart',
    buyNow: 'Buy Now',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    sold: 'sold',
    reviews: 'reviews',
    rating: 'rating',
    off: 'OFF',
    freeShipping: 'Free Shipping',
    onOrdersOver: 'on orders over',
    fastDelivery: 'Fast Delivery',
    securePayment: 'Secure Payment',
    buyerProtection: 'Buyer Protection',
    priceRange: 'Price Range',
    minPrice: 'Min price',
    maxPrice: 'Max price',
    apply: 'Apply',
    clear: 'Clear',
    clearAll: 'Clear All',
    filters: 'Filters',
    sortBy: 'Sort By',
    relevance: 'Relevance',
    priceLowHigh: 'Price: Low to High',
    priceHighLow: 'Price: High to Low',
    newestArrivals: 'Newest Arrivals',
    customerRating: 'Customer Rating',
    mostSold: 'Most Sold',
    brand: 'Brand',
    brands: 'Brands',
    shippingLocation: 'Shipping Location',
    shipsFrom: 'Ships from',
    results: 'results',
    noResults: 'No products found',
    noResultsDesc: 'Try adjusting your filters or search terms.',
    productDescription: 'Description',
    specifications: 'Specifications',
    customerReviews: 'Customer Reviews',
    relatedProducts: 'Related Products',
    youMayAlsoLike: 'You May Also Like',
    shipping: 'Shipping',
    shippingEstimate: 'Shipping Estimate',
    estimatedDelivery: 'Estimated delivery',
    days: 'days',
    variant: 'Variant',
    quantity: 'Quantity',
    color: 'Color',
    size: 'Size',
    writeReview: 'Write a Review',
    verifiedPurchase: 'Verified Purchase',
    helpful: 'Helpful',
    subtotal: 'Subtotal',
    discount: 'Discount',
    tax: 'Tax',
    total: 'Total',
    couponCode: 'Coupon Code',
    applyCoupon: 'Apply Coupon',
    couponApplied: 'Coupon applied!',
    invalidCoupon: 'Invalid or expired coupon',
    removeCoupon: 'Remove',
    free: 'Free',
    continueShopping: 'Continue Shopping',
    checkout: 'Checkout',
    emptyCart: 'Your cart is empty',
    emptyCartDesc: "Looks like you haven't added anything yet.",
    startShopping: 'Start Shopping',
    secureCheckout: 'Secure Checkout',
    shippingAddress: 'Shipping Address',
    paymentMethod: 'Payment Method',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    orderConfirmed: 'Order Confirmed!',
    orderConfirmedDesc: 'Thank you for your purchase. Your order number is',
    trackOrder: 'Track Order',
    email: 'Email',
    password: 'Password',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot password?',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    signInToContinue: 'Sign in to continue shopping',
    signUpToStart: 'Create your account to start',
    continueWith: 'Or continue with',
    myOrders: 'My Orders',
    myAddresses: 'My Addresses',
    myWishlist: 'My Wishlist',
    notifications: 'Notifications',
    returns: 'Returns & Refunds',
    profileSettings: 'Profile Settings',
    orderHistory: 'Order History',
    orderNumber: 'Order Number',
    orderDate: 'Order Date',
    orderStatus: 'Order Status',
    trackingNumber: 'Tracking Number',
    viewDetails: 'View Details',
    addAddress: 'Add Address',
    editAddress: 'Edit Address',
    deleteAddress: 'Delete Address',
    defaultAddress: 'Default',
    setDefault: 'Set as Default',
    markAllRead: 'Mark all read',
    noNotifications: 'No notifications yet',
    personalInfo: 'Personal Information',
    saveChanges: 'Save Changes',
    sellerDashboard: 'Seller Dashboard',
    overview: 'Overview',
    products: 'Products',
    inventory: 'Inventory',
    sellerOrders: 'Orders',
    analytics: 'Analytics',
    revenue: 'Revenue',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    stockLevel: 'Stock',
    price: 'Price',
    unitsSold: 'Units Sold',
    totalRevenue: 'Total Revenue',
    avgRating: 'Avg Rating',
    pendingOrders: 'Pending Orders',
    adminDashboard: 'Admin Dashboard',
    users: 'Users',
    manageProducts: 'Manage Products',
    manageCategories: 'Manage Categories',
    manageOrders: 'Manage Orders',
    managePayments: 'Manage Payments',
    manageCoupons: 'Manage Coupons',
    reports: 'Reports',
    totalUsers: 'Total Users',
    totalOrders: 'Total Orders',
    grossSales: 'Gross Sales',
    activeSellers: 'Active Sellers',
    liveChat: 'Live Chat',
    chatWithUs: 'Chat with us',
    typeMessage: 'Type a message...',
    online: 'Online',
    offline: 'Offline',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    loading: 'Loading...',
    currency: 'Currency',
    language: 'Language',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    theme: 'Theme',
    footerAbout: 'About ShopFlow',
    footerAboutDesc: 'A global multi-vendor marketplace connecting buyers and sellers with fast worldwide shipping and buyer protection.',
    customerService: 'Customer Service',
    helpCenter: 'Help Center',
    contactUs: 'Contact Us',
    returnsRefunds: 'Returns & Refunds',
    shippingInfo: 'Shipping Info',
    trackYourOrder: 'Track Your Order',
    aboutUs: 'About Us',
    careers: 'Careers',
    press: 'Press',
    blog: 'Blog',
    sellOnShopFlow: 'Sell on ShopFlow',
    sellerCenter: 'Seller Center',
    affiliateProgram: 'Affiliate Program',
    followUs: 'Follow Us',
    newsletter: 'Newsletter',
    newsletterDesc: 'Subscribe for exclusive deals and new arrivals',
    subscribe: 'Subscribe',
    emailPlaceholder: 'Enter your email',
    allRightsReserved: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    cookiePolicy: 'Cookie Policy',
    securePayment2: 'Secure Payment',
    moneyBackGuarantee: 'Money Back Guarantee',
    support247: '24/7 Support',
    flashDealEndsIn: 'Flash Deal ends in',
    daysLabel: 'Days',
    hours: 'Hours',
    minutes: 'Mins',
    seconds: 'Secs',
    offRetail: 'OFF RETAIL',
    chooseVariants: 'Choose Options',
    selectVariant: 'Select',
    only: 'Only',
    left: 'left',
    addedToCart: 'Added to cart',
    addedToWishlist: 'Added to wishlist',
    removedFromWishlist: 'Removed from wishlist',
    viewCart: 'View Cart',
    items: 'items',
    item: 'item',
    by: 'by',
    shipsTo: 'Ships to',
    worldwide: 'Worldwide',
    origin: 'Origin',
    guaranteed: 'Guaranteed',
    genuine: 'Genuine Product',
    description: 'Description',
    sku: 'SKU',
    availability: 'Availability',
    share: 'Share',
    compare: 'Compare',
    buyAgain: 'Buy Again',
    reorder: 'Reorder',
    status: 'Status',
    pending: 'Pending',
    paid: 'Paid',
    processing: 'Processing',
    shipped: 'Shipped',
    delivered: 'Delivered',
    cancelled: 'Cancelled',
    refunded: 'Refunded',
    order: 'Order',
    date: 'Date',
    qty: 'Qty',
    each: 'each',
    noOrders: 'No orders yet',
    noOrdersDesc: 'Your orders will appear here once you place them.',
    payWith: 'Pay with',
    creditCard: 'Credit Card',
    paypal: 'PayPal',
    applePay: 'Apple Pay',
    googlePay: 'Google Pay',
    cashOnDelivery: 'Cash on Delivery',
    cardNumber: 'Card Number',
    cardName: 'Cardholder Name',
    expiry: 'MM/YY',
    cvv: 'CVV',
    orderPlaced: 'Order Placed',
    paymentSuccess: 'Payment Successful',
    paymentSuccessDesc: 'Your payment has been processed successfully.',
    orderFailed: 'Payment Failed',
    tryAgain: 'Try Again',
    security: 'Your payment information is encrypted and secure',
    thanksForSubscribing: 'Thanks for subscribing!',
    welcomeBack: 'Welcome Back',
    newest: 'Newest',
    dealOfTheDay: 'Deal of the Day',
    limitedOffer: 'Limited Time Offer',
    superDeals: 'Super Deals',
    topPicks: 'Top Picks',
    trendingNow: 'Trending Now',
    mostPopular: 'Most Popular',
    exploreCategories: 'Explore Categories',
    exploreCategoriesDesc: 'Find exactly what you need',
    joinThousands: 'Join thousands of sellers worldwide',
    joinThousandsDesc: 'Start selling on ShopFlow today and reach millions of customers globally.',
    becomeSeller: 'Become a Seller',
    trustedBy: 'Trusted by millions worldwide',
    ratings: 'Ratings',
    active: 'Active',
    inactive: 'Inactive',
    verified: 'Verified',
    unverified: 'Unverified',
    sellerSince: 'Seller since',
    responseTime: 'Response time',
    chat: 'Chat',
    visit: 'Visit Store',
    close: 'Close',
    send: 'Send',
    chatWelcome: 'Hi! How can we help you today?',
    chatBotName: 'ShopFlow Assistant',
    aiRecommendations: 'AI Recommendations',
    pickForYou: 'Picks For You',
    seeMore: 'See More',
    youSaved: 'You saved',
    earnPoints: 'Earn loyalty points on every order',
    newArrivalsDesc: 'Fresh products added daily',
    exploreMore: 'Explore More',
    personalization: 'Personalized based on your browsing',
    freeReturns: 'Free Returns',
    daysReturn: '30-day returns',
    secureTransactions: 'Secure transactions',
    poweredBy: 'Powered by',
  },
  ar: {
    home: 'الرئيسية',
    catalog: 'الكتالوج',
    flashDeals: 'عروض الخاطفة',
    trending: 'الرائج',
    sellWithUs: 'بع معنا',
    search: 'ابحث عن المنتجات والعلامات والفئات...',
    searchPlaceholder: 'ابحث في ملايين المنتجات...',
    cart: 'السلة',
    wishlist: 'المفضلة',
    account: 'حسابي',
    signIn: 'تسجيل الدخول',
    signUp: 'إنشاء حساب',
    signOut: 'تسجيل الخروج',
    dashboard: 'لوحة التحكم',
    admin: 'الإدارة',
    seller: 'البائع',
    categories: 'الفئات',
    allCategories: 'جميع الفئات',
    featured: 'مميز',
    newArrivals: 'وصل حديثاً',
    topRated: 'الأعلى تقييماً',
    bestSellers: 'الأكثر مبيعاً',
    recommended: 'موصى به لك',
    recommendedDesc: 'اختيارات مدعومة بالذكاء الاصطناعي بناءً على نشاطك',
    viewAll: 'عرض الكل',
    shopNow: 'تسوق الآن',
    addToCart: 'أضف إلى السلة',
    buyNow: 'اشترِ الآن',
    outOfStock: 'نفذت الكمية',
    inStock: 'متوفر',
    sold: 'تم بيعه',
    reviews: 'مراجعات',
    rating: 'تقييم',
    off: 'خصم',
    freeShipping: 'شحن مجاني',
    onOrdersOver: 'لطلبات أكثر من',
    fastDelivery: 'توصيل سريع',
    securePayment: 'دفع آمن',
    buyerProtection: 'حماية المشتري',
    priceRange: 'نطاق السعر',
    minPrice: 'أقل سعر',
    maxPrice: 'أعلى سعر',
    apply: 'تطبيق',
    clear: 'مسح',
    clearAll: 'مسح الكل',
    filters: 'تصفية',
    sortBy: 'ترتيب حسب',
    relevance: 'الصلة',
    priceLowHigh: 'السعر: من الأقل للأعلى',
    priceHighLow: 'السعر: من الأعلى للأقل',
    newestArrivals: 'الأحدث',
    customerRating: 'تقييم العملاء',
    mostSold: 'الأكثر مبيعاً',
    brand: 'العلامة التجارية',
    brands: 'العلامات التجارية',
    shippingLocation: 'موقع الشحن',
    shipsFrom: 'يُشحن من',
    results: 'نتيجة',
    noResults: 'لا توجد منتجات',
    noResultsDesc: 'حاول تعديل عوامل التصفية أو كلمات البحث.',
    productDescription: 'الوصف',
    specifications: 'المواصفات',
    customerReviews: 'مراجعات العملاء',
    relatedProducts: 'منتجات ذات صلة',
    youMayAlsoLike: 'قد يعجبك أيضاً',
    shipping: 'الشحن',
    shippingEstimate: 'تقدير الشحن',
    estimatedDelivery: 'التوصيل المتوقع',
    days: 'أيام',
    variant: 'الخيار',
    quantity: 'الكمية',
    color: 'اللون',
    size: 'المقاس',
    writeReview: 'اكتب مراجعة',
    verifiedPurchase: 'عملية شراء موثقة',
    helpful: 'مفيد',
    subtotal: 'المجموع الفرعي',
    discount: 'الخصم',
    tax: 'الضريبة',
    total: 'الإجمالي',
    couponCode: 'رمز القسيمة',
    applyCoupon: 'تطبيق القسيمة',
    couponApplied: 'تم تطبيق القسيمة!',
    invalidCoupon: 'قسيمة غير صالحة أو منتهية',
    removeCoupon: 'إزالة',
    free: 'مجاني',
    continueShopping: 'متابعة التسوق',
    checkout: 'الدفع',
    emptyCart: 'سلتك فارغة',
    emptyCartDesc: 'يبدو أنك لم تضف أي شيء بعد.',
    startShopping: 'ابدأ التسوق',
    secureCheckout: 'دفع آمن',
    shippingAddress: 'عنوان الشحن',
    paymentMethod: 'طريقة الدفع',
    orderSummary: 'ملخص الطلب',
    placeOrder: 'تأكيد الطلب',
    orderConfirmed: 'تم تأكيد الطلب!',
    orderConfirmedDesc: 'شكراً لشرائك. رقم طلبك هو',
    trackOrder: 'تتبع الطلب',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    fullName: 'الاسم الكامل',
    confirmPassword: 'تأكيد كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    createAccount: 'إنشاء حساب',
    signInToContinue: 'سجل الدخول لمتابعة التسوق',
    signUpToStart: 'أنشئ حسابك للبدء',
    continueWith: 'أو تابع باستخدام',
    myOrders: 'طلباتي',
    myAddresses: 'عناويني',
    myWishlist: 'مفضلتي',
    notifications: 'الإشعارات',
    returns: 'الإرجاعات والمبالغ المستردة',
    profileSettings: 'إعدادات الحساب',
    orderHistory: 'سجل الطلبات',
    orderNumber: 'رقم الطلب',
    orderDate: 'تاريخ الطلب',
    orderStatus: 'حالة الطلب',
    trackingNumber: 'رقم التتبع',
    viewDetails: 'عرض التفاصيل',
    addAddress: 'إضافة عنوان',
    editAddress: 'تعديل العنوان',
    deleteAddress: 'حذف العنوان',
    defaultAddress: 'افتراضي',
    setDefault: 'تعيين كافتراضي',
    markAllRead: 'تعليم الكل كمقروء',
    noNotifications: 'لا توجد إشعارات بعد',
    personalInfo: 'المعلومات الشخصية',
    saveChanges: 'حفظ التغييرات',
    sellerDashboard: 'لوحة البائع',
    overview: 'نظرة عامة',
    products: 'المنتجات',
    inventory: 'المخزون',
    sellerOrders: 'الطلبات',
    analytics: 'التحليلات',
    revenue: 'الإيرادات',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل منتج',
    stockLevel: 'المخزون',
    price: 'السعر',
    unitsSold: 'الوحدات المباعة',
    totalRevenue: 'إجمالي الإيرادات',
    avgRating: 'متوسط التقييم',
    pendingOrders: 'الطلبات المعلقة',
    adminDashboard: 'لوحة الإدارة',
    users: 'المستخدمون',
    manageProducts: 'إدارة المنتجات',
    manageCategories: 'إدارة الفئات',
    manageOrders: 'إدارة الطلبات',
    managePayments: 'إدارة المدفوعات',
    manageCoupons: 'إدارة القسائم',
    reports: 'التقارير',
    totalUsers: 'إجمالي المستخدمين',
    totalOrders: 'إجمالي الطلبات',
    grossSales: 'إجمالي المبيعات',
    activeSellers: 'البائعون النشطون',
    liveChat: 'الدردشة المباشرة',
    chatWithUs: 'تحدث معنا',
    typeMessage: 'اكتب رسالة...',
    online: 'متصل',
    offline: 'غير متصل',
    back: 'رجوع',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    add: 'إضافة',
    loading: 'جارٍ التحميل...',
    currency: 'العملة',
    language: 'اللغة',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    theme: 'السمة',
    footerAbout: 'عن ShopFlow',
    footerAboutDesc: 'سوق عالمي متعدد البائعين يربط المشترين والبائعين مع شحن سريع عالمياً وحماية للمشتري.',
    customerService: 'خدمة العملاء',
    helpCenter: 'مركز المساعدة',
    contactUs: 'اتصل بنا',
    returnsRefunds: 'الإرجاعات والمبالغ المستردة',
    shippingInfo: 'معلومات الشحن',
    trackYourOrder: 'تتبع طلبك',
    aboutUs: 'من نحن',
    careers: 'الوظائف',
    press: 'الصحافة',
    blog: 'المدونة',
    sellOnShopFlow: 'بع على ShopFlow',
    sellerCenter: 'مركز البائع',
    affiliateProgram: 'برنامج التسويق',
    followUs: 'تابعنا',
    newsletter: 'النشرة البريدية',
    newsletterDesc: 'اشترك للحصول على عروض حصرية ومنتجات جديدة',
    subscribe: 'اشترك',
    emailPlaceholder: 'أدخل بريدك الإلكتروني',
    allRightsReserved: 'جميع الحقوق محفوظة',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    cookiePolicy: 'سياسة ملفات الارتباط',
    securePayment2: 'دفع آمن',
    moneyBackGuarantee: 'ضمان استرداد المال',
    support247: 'دعم 24/7',
    flashDealEndsIn: 'ينتهي العرض الخاطف خلال',
    daysLabel: 'أيام',
    hours: 'ساعات',
    minutes: 'دقائق',
    seconds: 'ثوانٍ',
    offRetail: 'خصم',
    chooseVariants: 'اختر الخيارات',
    selectVariant: 'اختر',
    only: 'فقط',
    left: 'متبقي',
    addedToCart: 'تمت الإضافة إلى السلة',
    addedToWishlist: 'تمت الإضافة إلى المفضلة',
    removedFromWishlist: 'تمت الإزالة من المفضلة',
    viewCart: 'عرض السلة',
    items: 'منتجات',
    item: 'منتج',
    by: 'بواسطة',
    shipsTo: 'يُشحن إلى',
    worldwide: 'عالمياً',
    origin: 'المنشأ',
    guaranteed: 'مضمون',
    genuine: 'منتج أصلي',
    description: 'الوصف',
    sku: 'رمز المنتج',
    availability: 'التوفر',
    share: 'مشاركة',
    compare: 'مقارنة',
    buyAgain: 'اشترِ مرة أخرى',
    reorder: 'إعادة الطلب',
    status: 'الحالة',
    pending: 'معلق',
    paid: 'مدفوع',
    processing: 'قيد المعالجة',
    shipped: 'تم الشحن',
    delivered: 'تم التوصيل',
    cancelled: 'ملغى',
    refunded: 'مسترد',
    order: 'طلب',
    date: 'التاريخ',
    qty: 'الكمية',
    each: 'للقطعة',
    noOrders: 'لا توجد طلبات بعد',
    noOrdersDesc: 'ستظهر طلباتك هنا بمجرد إتمامها.',
    payWith: 'ادفع باستخدام',
    creditCard: 'بطاقة ائتمان',
    paypal: 'PayPal',
    applePay: 'Apple Pay',
    googlePay: 'Google Pay',
    cashOnDelivery: 'الدفع عند الاستلام',
    cardNumber: 'رقم البطاقة',
    cardName: 'اسم حامل البطاقة',
    expiry: 'شهر/سنة',
    cvv: 'CVV',
    orderPlaced: 'تم تقديم الطلب',
    paymentSuccess: 'نجح الدفع',
    paymentSuccessDesc: 'تمت معالجة الدفع بنجاح.',
    orderFailed: 'فشل الدفع',
    tryAgain: 'حاول مرة أخرى',
    security: 'معلومات الدفع الخاصة بك مشفرة وآمنة',
    thanksForSubscribing: 'شكراً لاشتراكك!',
    welcomeBack: 'مرحباً بعودتك',
    newest: 'الأحدث',
    dealOfTheDay: 'صفقة اليوم',
    limitedOffer: 'عرض لفترة محدودة',
    superDeals: 'عروض مميزة',
    topPicks: 'أفضل الاختيارات',
    trendingNow: 'رائج الآن',
    mostPopular: 'الأكثر شعبية',
    exploreCategories: 'استكشف الفئات',
    exploreCategoriesDesc: 'اعثر على ما تريد بالضبط',
    joinThousands: 'انضم إلى آلاف البائعين حول العالم',
    joinThousandsDesc: 'ابدأ البيع على ShopFlow اليوم وصل إلى ملايين العملاء حول العالم.',
    becomeSeller: 'كن بائعاً',
    trustedBy: 'موثوق به من ملايين حول العالم',
    ratings: 'التقييمات',
    active: 'نشط',
    inactive: 'غير نشط',
    verified: 'موثق',
    unverified: 'غير موثق',
    sellerSince: 'بائع منذ',
    responseTime: 'وقت الاستجابة',
    chat: 'دردشة',
    visit: 'زيارة المتجر',
    close: 'إغلاق',
    send: 'إرسال',
    chatWelcome: 'مرحباً! كيف يمكننا مساعدتك اليوم؟',
    chatBotName: 'مساعد ShopFlow',
    aiRecommendations: 'توصيات الذكاء الاصطناعي',
    pickForYou: 'اختيارات لك',
    seeMore: 'المزيد',
    youSaved: 'وفّرت',
    earnPoints: 'اكسب نقاط ولاء مع كل طلب',
    newArrivalsDesc: 'منتجات جديدة تُضاف يومياً',
    exploreMore: 'استكشف المزيد',
    personalization: 'مخصص بناءً على تصفحك',
    freeReturns: 'إرجاع مجاني',
    daysReturn: 'إرجاع خلال 30 يوماً',
    secureTransactions: 'معاملات آمنة',
    poweredBy: 'مدعوم بـ',
  },
} as const;

export type Dictionary = (typeof dictionary)['en'];
export type TranslationKey = keyof Dictionary;

export function t(lang: LanguageCode, key: TranslationKey): string {
  return dictionary[lang][key] ?? dictionary.en[key] ?? key;
}
